### ISSUE TITLE
Mobile and desktop hosts 

### ISSUE THREAD

**Issue by gedw99** [loopholelabs/scale#77]
Would be cool to use the wasm functions with mobile and desktop and web apps using only golang

**Comment by ShivanshVij** [comment]
I’m willing to bet the typescript runtime will work fine in electron apps without any changes. 

What frameworks were you imagining writing the mobile/desktop/web apps in?

**Comment by trezy** [comment]
I'm closing this issue. If you'd like it reopened, leave a comment with your use case.
