### ISSUE TITLE
[Feature Request] Is it possible to push/pull the function to an OCI compatible registry?

### ISSUE THREAD

**Issue by heww** [loopholelabs/scale#85]
## Acceptance Criteria

* `scale fn oci-push` exists
  * Before pushing, Scale transforms the Scale Function and Signature into an OCI
  * The OCI is pushed to the destination registry
* `scale fn oci-pull` exists
  * The OCI is pulled from the source registry
  * After pulling, Scale transforms the OCI back to a regular Scale Function and Signature

## Questions

* ~How could we pass function params and get the appropriate output from the registry?~
  * The OCI just describes a root file system and doesn't care about the file contents.
  * We could include both a signature and a function in a `.tar.gz` file that gets pushed to the registry.
* ~Would the OCI include the runner?~
  * Nope, we'd just build an unpacking step.

**Comment by ShivanshVij** [comment]
The more we talk about this internally, the more it seems like that could make sense. 

There are downsides to this approach (namely that we can't modify/transform your code at the registry layer, all modifications have to happen locally before you push to the registry). 

At the same time, we gain access to the myriad of OCI-compliant registries. 

It's a nuanced issue, and I think the best thing to do is wait until the Signatures V1 release (which is coming soon, join our [discord](https://loopholelabs.io/discord)!) and then once we have enough users of that we can have a proper community meeting to make a decision on this.

**Comment by Handfish** [comment]
+1 to wanting OCI-compatible registry support. It would allow to easier adoption in a corporate setting. I would even prefer to run modifications locally.

**Comment by dphilla** [comment]
This will likely be part of future plans, but at this time is out of our current scope. However, we are definitely open to community contributions for this feature :)
