### ISSUE TITLE
Typescript Host: mutate the context does not work

### ISSUE THREAD

**Issue by Yuyz0112** [loopholelabs/scale#87]
In my Go Guest code, I have:

```go
//go:build tinygo || js || wasm

package scale

import (
	signature "github.com/loopholelabs/scale-signature-http"
)

func Scale(ctx *signature.Context) (*signature.Context, error) {
	ctx.Response().SetBody("test: " + ctx.Request().Method())
	return ctx.Next()
}
```

And it will return `test: GET` when I curl the endpoint of the `scale run` process.

But when I embed the exported `.scale` file into a Typescript Host like this:

```ts
// init things...
const ctx= i.Context();
ctx.Request.Method = "PUT";
console.log(ctx)
i.Run();
console.log(new TextDecoder().decode(i.Context().Response.Body));
```

The first console print the context object as below so I think the mutation works:

```
<ref *1> Context {
  _Request: HttpRequest {
    _Method: 'PUT',
    _URI: '',
    _ContentLength: 0n,
    _Protocol: '',
    _IP: '',
    _Body: Uint8Array(0) [],
    _Headers: Map(0) {}
  },
  _Response: HttpResponse {
    _StatusCode: 0,
    _Body: Uint8Array(0) [],
    _Headers: Map(0) {}
  },
  runtimeContext: RuntimeContext { context: [Circular *1] }
}
```

And the second console shows the response from the embed function as:

```
test: 
```

So looks like the context in the Go Guest does not change.

**Comment by ShivanshVij** [comment]
This looks like a serialization bug on our end, we’re working on a fix

**Comment by ShivanshVij** [comment]
This issue should be fixed as part of https://github.com/loopholelabs/scale/releases/tag/v0.3.15 

To update your code you should make sure the `dependencies` section of your scalefile looks like this:

```yaml
dependencies:
  - name: github.com/loopholelabs/scale-signature
    version: v0.2.11
  - name: github.com/loopholelabs/scale-signature-http
    version: v0.3.8
```

**Comment by Yuyz0112** [comment]
Cool! I'll have a try.
